/** Clubs par championnat — saison 2025-26 */
export const CLUBS_BY_LEAGUE: Record<string, string[]> = {
  "Ligue 1": [
    "Paris Saint-Germain",
    "Olympique Marseille",
    "AS Monaco",
    "Olympique Lyonnais",
    "Lille OSC",
    "OGC Nice",
    "RC Lens",
    "Stade Rennais",
    "RC Strasbourg",
    "Toulouse FC",
    "Stade Brestois",
    "FC Nantes",
    "Stade de Reims",
    "AJ Auxerre",
    "Angers SCO",
    "Le Havre AC",
    "AS Saint-Étienne",
    "Montpellier HSC",
  ],
  "Ligue 2": [
    "Paris FC",
    "FC Lorient",
    "FC Metz",
    "ESTAC Troyes",
    "Stade Lavallois",
    "AC Ajaccio",
    "Pau FC",
    "Rodez AF",
    "Amiens SC",
    "En Avant Guingamp",
    "SC Bastia",
    "USL Dunkerque",
    "Annecy FC",
    "Red Star FC",
    "FC Martigues",
    "Clermont Foot",
    "Grenoble Foot 38",
    "SM Caen",
    "US Boulogne",
    "Valenciennes FC",
  ],
  "Premier League": [
    "Arsenal",
    "Aston Villa",
    "AFC Bournemouth",
    "Brentford FC",
    "Brighton & Hove Albion",
    "Chelsea FC",
    "Crystal Palace",
    "Everton FC",
    "Fulham FC",
    "Ipswich Town",
    "Leicester City",
    "Liverpool FC",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Southampton FC",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton Wanderers",
  ],
  "La Liga": [
    "Real Madrid",
    "FC Barcelona",
    "Atlético Madrid",
    "Sevilla FC",
    "Real Sociedad",
    "Villarreal CF",
    "Real Betis",
    "Valencia CF",
    "Athletic Club",
    "CA Osasuna",
    "Getafe CF",
    "Girona FC",
    "RCD Mallorca",
    "Rayo Vallecano",
    "RC Celta de Vigo",
    "UD Las Palmas",
    "Deportivo Alavés",
    "Real Valladolid",
    "RCD Espanyol",
    "CD Leganés",
  ],
  "Serie A": [
    "Inter Milan",
    "AC Milan",
    "Juventus FC",
    "SSC Napoli",
    "AS Roma",
    "SS Lazio",
    "Atalanta BC",
    "ACF Fiorentina",
    "Bologna FC",
    "Torino FC",
    "AC Monza",
    "Genoa CFC",
    "Udinese Calcio",
    "Hellas Verona",
    "US Lecce",
    "Cagliari Calcio",
    "Empoli FC",
    "Parma Calcio",
    "Venezia FC",
    "Como 1907",
  ],
}

export const LEAGUE_OPTIONS = ["Tous", ...Object.keys(CLUBS_BY_LEAGUE)] as const
