/**
 * Clubs par championnat — saison 2026-2027.
 * Compositions vérifiées (promotions/relégations) via Wikipédia et sources
 * spécialisées en septembre 2026. Ligue 2 est passée à 18 clubs (comme
 * Ligue 1) depuis la réforme de 2024-25.
 */
export const CLUBS_BY_LEAGUE: Record<string, string[]> = {
  "Ligue 1": [
    "Paris Saint-Germain",
    "Olympique Marseille",
    "AS Monaco",
    "Olympique Lyonnais",
    "Lille OSC",
    "OGC Nice",
    "RC Lens",
    "Stade Rennais",
    "RC Strasbourg",
    "Toulouse FC",
    "Stade Brestois",
    "FC Lorient",
    "Paris FC",
    "Angers SCO",
    "Le Havre AC",
    "AJ Auxerre",
    "ESTAC Troyes",
    "Le Mans FC",
  ],
  "Ligue 2": [
    "AS Saint-Étienne",
    "Stade de Reims",
    "Montpellier HSC",
    "FC Nantes",
    "FC Metz",
    "Annecy FC",
    "Red Star FC",
    "Rodez AF",
    "AS Nancy Lorraine",
    "FC Sochaux-Montbéliard",
    "USL Dunkerque",
    "Pau FC",
    "En Avant Guingamp",
    "US Boulogne",
    "Clermont Foot",
    "Grenoble Foot 38",
    "Stade Lavallois",
    "Dijon FCO",
  ],
  "Premier League": [
    "Arsenal",
    "Aston Villa",
    "AFC Bournemouth",
    "Brentford FC",
    "Brighton & Hove Albion",
    "Chelsea FC",
    "Coventry City",
    "Crystal Palace",
    "Everton FC",
    "Fulham FC",
    "Hull City",
    "Ipswich Town",
    "Leeds United",
    "Liverpool FC",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sunderland AFC",
    "Tottenham Hotspur",
  ],
  "La Liga": [
    "Real Madrid",
    "FC Barcelona",
    "Atlético Madrid",
    "Sevilla FC",
    "Real Sociedad",
    "Villarreal CF",
    "Real Betis",
    "Valencia CF",
    "Athletic Club",
    "CA Osasuna",
    "Getafe CF",
    "RCD Espanyol",
    "Rayo Vallecano",
    "RC Celta de Vigo",
    "Deportivo Alavés",
    "Levante UD",
    "Elche CF",
    "Racing de Santander",
    "RC Deportivo La Coruña",
    "Málaga CF",
  ],
  "Serie A": [
    "Inter Milan",
    "AC Milan",
    "Juventus FC",
    "SSC Napoli",
    "AS Roma",
    "SS Lazio",
    "Atalanta BC",
    "ACF Fiorentina",
    "Bologna FC",
    "Torino FC",
    "AC Monza",
    "Genoa CFC",
    "Udinese Calcio",
    "US Lecce",
    "Cagliari Calcio",
    "Parma Calcio",
    "Venezia FC",
    "Como 1907",
    "US Sassuolo",
    "Frosinone Calcio",
  ],
  Bundesliga: [
    "Bayern Munich",
    "Borussia Dortmund",
    "Bayer Leverkusen",
    "RB Leipzig",
    "VfB Stuttgart",
    "Eintracht Frankfurt",
    "SC Freiburg",
    "TSG Hoffenheim",
    "Borussia Mönchengladbach",
    "Werder Bremen",
    "1. FSV Mainz 05",
    "FC Augsburg",
    "1. FC Union Berlin",
    "Hamburger SV",
    "1. FC Köln",
    "FC Schalke 04",
    "SV Elversberg",
    "SC Paderborn 07",
  ],
}

/**
 * Catégories gérées entièrement depuis l'admin (base de données), en plus
 * des championnats ci-dessus : "Pays/Nations" pour les équipes nationales,
 * "Autre" pour tout maillot qui ne rentre dans aucun championnat du site.
 * Voir src/lib/db-catalog.ts.
 */
export const CUSTOM_LEAGUES = ["Pays/Nations", "Autre"] as const
export type CustomLeague = (typeof CUSTOM_LEAGUES)[number]

export const LEAGUE_OPTIONS = ["Accueil", ...Object.keys(CLUBS_BY_LEAGUE), ...CUSTOM_LEAGUES] as const
