"use client"

import { useEffect, useState } from "react"
import { X } from "lucide-react"

export function NewsletterPopup() {
  const [open, setOpen] = useState(false); const [email, setEmail] = useState(""); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle")
  useEffect(() => { if (!sessionStorage.getItem("elite-newsletter-closed")) { const timer = window.setTimeout(() => setOpen(true), 700); return () => clearTimeout(timer) } }, [])
  function close() { sessionStorage.setItem("elite-newsletter-closed", "1"); setOpen(false) }
  async function subscribe(event: React.FormEvent) { event.preventDefault(); setStatus("sending"); const res = await fetch("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); setStatus(res.ok ? "sent" : "error") }
  if (!open) return null
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/75 p-4" role="dialog" aria-modal="true" aria-label="Inscription newsletter"><section className="relative w-full max-w-[540px] overflow-hidden rounded-[28px] bg-gradient-to-br from-blue-800 to-blue-950 text-white shadow-2xl"><div className="pointer-events-none absolute -right-20 -top-20 size-64 rounded-full bg-blue-400/20" /><div className="pointer-events-none absolute -bottom-24 -left-20 size-72 rounded-full border-[28px] border-white/10" /><button onClick={close} aria-label="Fermer" className="absolute right-4 top-4 z-10 grid size-10 place-items-center rounded-full bg-white text-blue-950 shadow-lg hover:bg-blue-100"><X /></button><div className="relative px-6 py-10 text-center sm:px-12"><p className="text-xs font-black uppercase tracking-[0.24em] text-blue-200">EliteFootballShop</p><h2 className="mt-3 text-4xl font-black italic leading-none sm:text-5xl">LE CLUB DES<br /><span className="text-blue-200">PASSIONNÉS</span></h2><p className="mx-auto mt-5 max-w-md text-sm font-medium leading-6 text-blue-50">Recevez nos nouveautés, nos maillots en vedette et une réduction de bienvenue pour votre première commande.</p>{status === "sent" ? <><div className="mt-8 rounded-2xl bg-emerald-500/20 px-5 py-4 text-sm font-bold text-emerald-50">Bienvenue dans le club ! Votre inscription est confirmée.</div><button onClick={close} className="mt-5 w-full rounded-xl bg-white py-3.5 text-sm font-black text-blue-950 hover:bg-blue-100">Fermer</button></> : <><form onSubmit={subscribe} className="mx-auto mt-8 max-w-sm"><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Votre adresse e-mail" className="w-full rounded-xl border border-white/30 bg-white/90 px-4 py-3 text-sm text-slate-900 outline-none placeholder:text-slate-500 focus:ring-4 focus:ring-blue-300/50" /><label className="mt-3 flex items-start gap-2 text-left text-xs text-blue-100"><input required type="checkbox" className="mt-0.5 size-4 accent-blue-700" />J’accepte de recevoir les nouveautés et offres EliteFootballShop.</label>{status === "error" && <p className="mt-3 text-xs font-semibold text-red-200">Une erreur est survenue. Réessayez.</p>}<button disabled={status === "sending"} className="mt-5 w-full rounded-xl bg-blue-700 py-3.5 text-sm font-black uppercase tracking-wide text-white shadow-lg shadow-blue-950/40 hover:bg-blue-600 disabled:opacity-60">{status === "sending" ? "Inscription…" : "Je m’inscris"}</button></form><button onClick={close} className="mt-5 text-xs font-semibold text-blue-200 underline underline-offset-4 hover:text-white">Non merci, continuer ma visite</button></>}</div></section></div>
}
