import { notFound } from "next/navigation"
import { prisma } from "@/lib/prisma"
import { formatEuro, orderLabel } from "@/lib/admin"
import { PageHeader, StatusBadge } from "@/components/admin/AdminUi"
import { OrderStatusForm } from "@/components/admin/OrderStatusForm"

export default async function OrderDetailPage({ params }: PageProps<"/admin/orders/[id]">) {
  const { id } = await params; const order = await prisma.order.findUnique({ where: { id }, include: { user: true, items: { include: { product: true } } } }); if (!order) notFound()
  const address = order.shippingAddress as Record<string, string> | null
  return <><PageHeader title={`Commande #${order.id.slice(-8).toUpperCase()}`} description={`Créée le ${order.createdAt.toLocaleString("fr-FR")}`} action={<OrderStatusForm id={order.id} status={order.status} shippingStatus={order.shippingStatus} />} /><div className="grid gap-6 lg:grid-cols-3"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 lg:col-span-2"><h2 className="font-bold text-blue-950">Articles</h2><div className="mt-4 divide-y">{order.items.length ? order.items.map((item) => <div className="flex items-center justify-between py-3" key={item.id}><div><p className="font-semibold">{item.productName || item.product?.name || "Article"}</p><p className="text-xs text-slate-500">Taille {item.size} · Quantité {item.quantity}</p></div><p className="font-bold">{formatEuro(item.price * item.quantity)}</p></div>) : <p className="py-5 text-sm text-slate-500">Cette ancienne commande ne contient pas encore le détail de ses articles.</p>}</div><div className="mt-4 flex justify-between border-t pt-4 font-black"><span>Total</span><span>{formatEuro(order.total)}</span></div></section><aside className="space-y-6"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold text-blue-950">Client</h2><p className="mt-3 font-semibold">{order.user?.name || "Client invité"}</p><p className="text-sm text-slate-500">{order.user?.email || order.guestEmail || "Email non disponible"}</p>{address && <p className="mt-3 text-sm text-slate-600">{[address.prenom, address.nom, address.numero, address.adresse, address.codePostal, address.ville, address.pays].filter(Boolean).join(" · ")}</p>}</section><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold text-blue-950">Paiement & livraison</h2><div className="mt-3 space-y-2 text-sm"><p>Paiement : <StatusBadge value={order.paymentStatus} /></p><p>Commande : <StatusBadge value={order.status} /></p><p>Livraison : <StatusBadge value={order.shippingStatus} /></p>{order.stripeId && <p className="break-all text-xs text-slate-500">Stripe : {order.stripeId}</p>}</div></section></aside></div></>
}
