"use client"

import { useState } from "react"
import Link from "next/link"
import { PromoBanner } from "@/components/catalog/PromoBanner"

const inputClass = "w-full rounded-xl border border-blue-100 bg-white px-3 py-2.5 text-sm shadow-sm outline-none transition focus:border-blue-600 focus:ring-4 focus:ring-blue-100"

export default function ContactPage() {
  const [nom, setNom] = useState(""); const [email, setEmail] = useState(""); const [sujet, setSujet] = useState(""); const [message, setMessage] = useState(""); const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [error, setError] = useState("")
  async function submit(event: React.FormEvent) { event.preventDefault(); setState("sending"); setError(""); const res = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: nom, email, subject: sujet, message }) }); if (res.ok) { setState("sent"); setNom(""); setEmail(""); setSujet(""); setMessage("") } else { const data = await res.json().catch(() => ({})); setError(data.error || "L’envoi a échoué."); setState("error") } }
  return <div className="min-h-screen bg-[#edf4ff] font-[family-name:var(--font-inter)]"><PromoBanner /><header className="border-b border-blue-100 bg-white/90"><div className="mx-auto flex h-14 max-w-3xl items-center justify-between px-4"><Link href="/" className="text-sm font-semibold text-blue-950 hover:text-blue-700">← Retour à la boutique</Link><span className="font-black italic text-blue-950">L&apos;ÂME DU MAILLOT</span></div></header><main className="mx-auto max-w-3xl px-4 py-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-800">Support EliteFootballShop</p><h1 className="mt-2 text-3xl font-black text-blue-950">Comment pouvons-nous vous aider ?</h1><p className="mt-2 text-sm text-slate-600">Votre message arrive directement dans notre espace support. Notre équipe vous répond sous 24 à 48 h.</p><form onSubmit={submit} className="mt-8 space-y-4 rounded-3xl border border-blue-100 bg-white p-6 shadow-xl shadow-blue-950/5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Votre nom<input required value={nom} onChange={(e) => setNom(e.target.value)} className={`${inputClass} mt-1.5`} /></label><label className="text-xs font-bold text-slate-600">Votre e-mail<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className={`${inputClass} mt-1.5`} /></label></div><label className="block text-xs font-bold text-slate-600">Sujet<select required value={sujet} onChange={(e) => setSujet(e.target.value)} className={`${inputClass} mt-1.5`}><option value="">Choisir un sujet</option><option>Question sur ma commande</option><option>Problème de livraison</option><option>Question sur un maillot</option><option>Problème de paiement</option><option>Autre question</option></select></label><label className="block text-xs font-bold text-slate-600">Message<textarea required rows={6} value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Décrivez votre question ou problème…" className={`${inputClass} mt-1.5 resize-none`} /></label>{state === "sent" && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-700">Message envoyé. Nous vous répondrons par e-mail.</p>}{state === "error" && <p className="rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</p>}<button disabled={state === "sending"} className="w-full rounded-xl bg-blue-950 py-3.5 text-sm font-black text-white shadow-lg shadow-blue-900/20 transition hover:bg-blue-800 disabled:opacity-60">{state === "sending" ? "Envoi…" : "Envoyer mon message"}</button></form></main></div>
}
