import Link from "next/link"
import { prisma } from "@/lib/prisma"
import { formatEuro } from "@/lib/admin"
import { EmptyState, PageHeader, StatusBadge } from "@/components/admin/AdminUi"

export const dynamic = "force-dynamic"
export default async function OrdersPage({ searchParams }: PageProps<"/admin/orders">) {
  const { q = "", status = "" } = await searchParams
  const query = typeof q === "string" ? q.trim() : ""; const selected = typeof status === "string" ? status : ""
  const orders = await prisma.order.findMany({ where: { ...(selected ? { status: selected as never } : {}), ...(query ? { OR: [{ id: { contains: query, mode: "insensitive" } }, { guestEmail: { contains: query, mode: "insensitive" } }, { user: { is: { OR: [{ name: { contains: query, mode: "insensitive" } }, { email: { contains: query, mode: "insensitive" } }] } } }] } : {}) }, include: { user: { select: { name: true, email: true } }, items: true }, orderBy: { createdAt: "desc" }, take: 50 })
  return <><PageHeader title="Commandes" description="Suivez les paiements et l’avancement des commandes sur demande." /><form className="mb-5 flex flex-wrap gap-3"><input name="q" defaultValue={query} placeholder="Numéro, client ou email" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" /><select name="status" defaultValue={selected} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">Tous les statuts</option>{["PENDING","PAID","SHIPPED","DELIVERED","CANCELLED"].map((s) => <option key={s}>{s}</option>)}</select><button className="rounded-lg bg-blue-950 px-4 py-2 text-sm font-bold text-white">Filtrer</button></form>{orders.length ? <div className="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Commande</th><th>Client</th><th>Date</th><th>Produits</th><th>Montant</th><th>Statut</th><th></th></tr></thead><tbody>{orders.map((order) => <tr className="border-b last:border-0" key={order.id}><td className="p-4 font-bold">#{order.id.slice(-8).toUpperCase()}</td><td><p>{order.user?.name || "Client invité"}</p><p className="text-xs text-slate-500">{order.user?.email || order.guestEmail || "—"}</p></td><td>{order.createdAt.toLocaleDateString("fr-FR")}</td><td>{order.items.length}</td><td className="font-bold">{formatEuro(order.total)}</td><td><StatusBadge value={order.status} /></td><td className="p-4"><Link className="font-semibold text-blue-800" href={`/admin/orders/${order.id}`}>Ouvrir</Link></td></tr>)}</tbody></table></div> : <EmptyState>Aucune commande ne correspond à cette recherche.</EmptyState>}</>
}
